---
title: "UCSB domestic grad enrollment"
author: "Marco Palombo"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

# attach packages
library(tidyverse)
library(here)

```

```{r}
ucsb_grad <- read_csv(here("data", "ucsb_grad_data.csv"))
```

```{r}
ggplot(data = ucsb_grad, aes(x = year_abbr, y = domestic_enrollment, color = ethnicity, fill = ethnicity)) +
  geom_col(position = "fill", width = .8) +
  scale_fill_gradient() +
  labs(x = "Year", y = "Domestic enrollment", title = "UCSB Domestic Graduate Student Ethnicity") +
  theme_minimal()+
  scale_color_manual(values = c("orchid","lightgoldenrod","cyan",
                                "plum","indianred","seagreen2","salmon",
                                "tan","turquoise3","lavender"))+
   scale_fill_manual(values = c("orchid","lightgoldenrod","cyan",
                                "plum","indianred","seagreen2","salmon",
                                "tan","turquoise3","lavender"))
```

**Figure 1:** Breakdown of UCSB domestic graduate student ethnicity from 2008-2019.
Data: "Campus Profiles." UC Santa Barbara Office of Budget & Planning." https://bap.ucsb.edu/institutional-research/campus-profiles 
